version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  database:
    image: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
 